name: CI
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MODEL_NAME: sshleifer/tiny-gpt2
      QUANTIZATION: none
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest modal fastapi uvicorn
      - name: Unit tests
        run: pytest -q
      - name: Inference smoke
        run: python -m modules.phi2_inference --smoke
