name: CI
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MODEL_NAME: sshleifer/tiny-gpt2
      QUANTIZATION: none
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Security scanning
        run: |
          pip-audit --desc --format=json --output=security-report.json || true
          bandit -r . -f json -o bandit-report.json || true
      - name: Unit tests
        run: pytest -q
      - name: Inference smoke
        run: python -m modules.phi2_inference --smoke
