name: CI
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MODEL_NAME: sshleifer/tiny-gpt2
      QUANTIZATION: none
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Run security audit
        run: |
          pip-audit --desc --format=json --output=audit-report.json || true
          bandit -r . -f json -o bandit-report.json || true
      - name: Generate SBOM
        run: |
          cyclonedx-py requirements requirements.txt -o sbom.json
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compliance-reports
          path: |
            audit-report.json
            bandit-report.json
            sbom.json
      - name: Unit tests
        run: pytest -q
      - name: Inference smoke
        run: python -m modules.phi2_inference --smoke
