name: Deploy to Modal

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: modal-deploy
      cancel-in-progress: false

    env:
      MODAL_TOKEN_ID: ${{ secrets.MODAL_TOKEN_ID }}
      MODAL_TOKEN_SECRET: ${{ secrets.MODAL_TOKEN_SECRET }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Modal CLI
        run: pip install --upgrade pip modal

      - name: Check secrets availability
        run: |
          echo "Checking if secrets are available..."
          if [ -z "$MODAL_TOKEN_ID" ]; then echo "MODAL_TOKEN_ID is empty"; exit 1; fi
          if [ -z "$MODAL_TOKEN_SECRET" ]; then echo "MODAL_TOKEN_SECRET is empty"; exit 1; fi
          echo "Secrets are available"

      - name: Deploy async app to Modal
        working-directory: ./
        run: |
          echo "Setting up Modal authentication..."
          modal token set --token-id "$MODAL_TOKEN_ID" --token-secret "$MODAL_TOKEN_SECRET"
          echo "Deploying to Modal..."
          modal deploy modal_deploy_async.py --name logsense-async
