[server]
maxMessageSize = 300
port = 8000
address = "0.0.0.0"
headless = true
enableCORS = false
enableXsrfProtection = false
fileWatcherType = "none"

[theme]
# Corporate blue theme
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#262730"
font = "sans serif"

[browser]
gatherUsageStats = false
